# Generated by Django 3.2.9 on 2021-12-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
